package handler

import (
	// docs is generated by Swag CLI, you have to import it.
	_ "github.com/Fachrulmustofa20/bank-example.git/docs"
	"github.com/Fachrulmustofa20/bank-example.git/middleware"
	"github.com/Fachrulmustofa20/bank-example.git/service"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

type Handler struct {
	userUsecase    service.UsersUsecase
	balanceUsecase service.BalanceUsecase
	bankUsecase    service.BankUsecase
}

func NewUserHandler(r *gin.Engine,
	userUsecase service.UsersUsecase,
	balanceUsecase service.BalanceUsecase,
	bankUsecase service.BankUsecase,
) {
	handler := &Handler{
		userUsecase:    userUsecase,
		balanceUsecase: balanceUsecase,
		bankUsecase:    bankUsecase,
	}
	// test
	r.GET("/api/welcome", handler.Welcome)

	// users
	r.POST("/api/users/register", handler.Register)
	r.POST("/api/users/login", handler.Login)
	r.GET("/api/users/profile", middleware.Authentication(), handler.Profile)

	// banks
	r.POST("/api/bank/account", middleware.Authentication(), handler.CreateAccountBank)
	r.PUT("/api/bank/deposit", middleware.Authentication(), handler.AddDeposit)

	// balance
	r.GET("/api/balance", middleware.Authentication(), handler.GetBalance)
	r.POST("/api/balance/top-up", middleware.Authentication(), handler.TopUpBalance)
	r.POST("/api/balance/transfer", middleware.Authentication(), handler.TransferBalance)
	r.GET("/api/balance/mutation", middleware.Authentication(), handler.GetMutationBalance)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}
